// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmgksllxvocbzuhyxkaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZ2tzbGx4dm9jYnp1aHl4a2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDY1NTUsImV4cCI6MjA1NDE4MjU1NX0.WgFUGEqHOKvJayxW-OPyNEIjQ4vvqGh8Dig3eI1MnD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);